version: "3.3"

services:
  app:
    container_name: ja-sa
    image: ja_sa:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    env_file:
      - .env
    volumes:
      - ./app:/app
